### PR TITLE
add company name

### PR DESCRIPTION
**Pull request by jhp0621**
Items addressed:
- [Add company name](https://app.asana.com/0/1203996148278240/1204018538936511/f)

Blockers: 
- [ ] none

QA steps:
- [ ] Navigate to home page
- [ ] Verify the company name shows up correctly

### CODE REVIEW

**Review by katespace — CHANGES_REQUESTED** [review]
Please remove "s"

**Review by katespace — APPROVED** [review]
LGTM

**Comment by jhp0621** [comment]
@katespace QA ready

**Comment by katespace** [comment]
QA passed!

**Pull request merged**
